apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-grpc-service
  namespace: dev
spec:
  selector:
    matchLabels:
      name: node-grpc-service
  template:
    metadata:
      labels:
        name: node-grpc-service
    spec:
      containers:
      - name: node-grpc-service
        image: node-grpc-service
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: node-grpc-service
  namespace: dev
  labels:
    name: node-grpc-service
spec:
  selector:
    name: node-grpc-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
